version: '2'

services:
  rest:
    build: ./rest
    container_name: rest
    image: appdynamics/sample-app-rest
    links:
      - db1
    ports: 
      - "8080:8080"

  db1:
    container_name: db1
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=singcontroller  
    ports: 
      - "3306:3306"

  web:
    build: ./web
    container_name: web
    image: appdynamics/sample-app-web
    links:
      - rest
      - db1
    ports:
      - "3000:3000"


